name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Load Cached Poetry
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: /home/runner/.local
          key: poetry-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}

      - name: Add Cached Poetry to PATH
        if: steps.cached-poetry.outputs.cache-hit == 'true'
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-in-project: true

      - name: Load Cached Virtualenv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry config virtualenvs.in-project true && poetry install --no-interaction --no-root
