### >>> basic release without commitizen, based i.e. "git tag v0.1.4" and "git push origin v0.1.4"

name: Release

# run on every commit tag which begins with "v" (e.g., "v0.1.4") on the "main" branch
on:
  push:
    branches:
      - main

# create a GH release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build and test
        run: |
          echo "done!"

      - name: Update Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
